### ISSUE TITLE
Optimoroute THU CW18

### ISSUE THREAD

**Issue by Amarillyde** [ozika/good_bank#4]
One email is in the upcoming file but did not come up in the optimoroute THU CW18 file.
Reason: she probably re-activated her account today, so her date in the upcoming from was 5/05, and all the others 6/05. We have already had a case like this... :P

**Comment by ozika** [comment]
Great, thanks! Okay, let's think about how to prevent it, any ideas?

**Comment by Amarillyde** [comment]
Yes, the script should take from the upcoming file all the orders with the date we are planning for and any eventual order with a previous date (which normally would be zero).
